### ISSUE TITLE
Is it possible to prove trig identities?

### ISSUE THREAD

**Issue by danbst** [mirefek/geo_logic#2]
Is it possible to prove 
```
XBC == XAE
AD == AB (cos BAX cos XAE - sin BAX sin XAE )
```
![image](https://user-images.githubusercontent.com/743057/126049187-c83857df-c4b2-490f-b560-60cf64d8fb09.png)

```
_ ->
  A <- free_point 0.0 0.0
  a <- m_line 1.0 A
  p <- perpline a A
  b <- m_circle_with_center 1.0 A
  c <- m_line -0.09210043086516115 A
  d <- m_line -0.3086204509945808 A
  B <- intersection 0 d b
  e <- perpline c B
  X <- intersection c e
  f <- perpline a X
  g <- perpline a B
  h <- perpline g X
  C <- intersection h g
  D <- intersection a g
  E <- intersection a f
  i <- line A X

label__A -> pos:P
  pos <- free_point 0.0 -20.0
hide__c ->
label__c -> pos:D offset:D
  pos <- custom_ratio 0.1 0.0
  offset <- custom_ratio 20.0 0.0
label__B -> pos:P
  pos <- free_point 0.0 -20.0
label__X -> pos:P
  pos <- free_point 0.0 -20.0
label__h -> pos:D offset:D
  pos <- custom_ratio 0.1 0.0
  offset <- custom_ratio 20.0 0.0
label__C -> pos:P
  pos <- free_point 0.0 -20.0
label__D -> pos:P
  pos <- free_point 0.0 -20.0
label__E -> pos:P
  pos <- free_point 0.0 -20.0

view__data -> anchor:P zoom:D
  anchor <- free_point 0.0 -0.0
  zoom <- custom_ratio 200.0 0.
```

**Comment by mirefek** [comment]
Not really well.

The main issue is that Geologic's logic can't even state length identities with addition / subtraction. One could try to add addition / subtraction using constructions, and prove things about it (such as associativity of addition, inverse of addition / subtraction, addition on a line) but to me it feels that there could be annoying special cases at which the definition, or proofs could fail. So I haven't been really trying.

It would be better to add addition / subtraction on a primitive level but then there is a question of how much automation it should support. Checking equations involving only multiplication is much easier than checking equations with both addition and multiplication. On the other hand, I wouldn't like to turn GeoLogic into a tool accessing geometry through algebra.

On the other hand, the first step of triangles XBC, XAE being similar is easy -- that is
`  <- sim_aa B C X A E X`
After that, GeoLogic knows the ratios between the sides of lengths of the two triangles. The trigonometric functions are not defined in GeoLogic but it wouldn't be too hard. Reasoning about them are just similar right triangles.

**Comment by danbst** [comment]
Thanks for your answer! Hadn't though that addition would complicate things.
